"""Export helpers for sockLight — PAC, Privoxy, and Adblock filter formats."""

from __future__ import annotations

import datetime
from pathlib import Path

from socklight.filters import FilterEngine, FilterMode, RuleKind


def generate_pac(
    filter_engine: FilterEngine,
    classifier,
    proxy_host: str,
    proxy_port: int,
    path: Path,
) -> None:
    """Write a PAC file reflecting current filter rules and blocked categories."""
    proxy = f"{proxy_host}:{proxy_port}"
    deny_rules  = [r for r in filter_engine.rules if r.kind == RuleKind.DENY]
    allow_rules = [r for r in filter_engine.rules if r.kind == RuleKind.ALLOW]
    blocked_cats = [
        c for c in classifier.categories
        if classifier.is_category_blocked(c.name)
    ]

    out: list[str] = [
        f"// Generated by sockLight — SOCKS5 Dev Proxy — {datetime.date.today()}",
        f"// Proxy: SOCKS5 {proxy}  |  Mode: {filter_engine.mode.value}",
        "//",
        "// Usage:",
        f"//   chromium --proxy-pac-url=\"file://{path.resolve()}\"",
        f"//   firefox  --proxy-server=\"pac+file://{path.resolve()}\"",
        "",
        "function FindProxyForURL(url, host) {",
        "    host = host.toLowerCase();",
        "",
    ]

    def _pat(rule) -> str:
        if rule.port:
            return (
                f'shExpMatch(host, "{rule.pattern}") && '
                f'url.indexOf(":{rule.port}") !== -1'
            )
        return f'shExpMatch(host, "{rule.pattern}")'

    if deny_rules:
        out.append("    // Deny rules")
        for r in deny_rules:
            out.append(f'    if ({_pat(r)}) return "PROXY 127.0.0.1:1";')
        out.append("")

    if blocked_cats:
        out.append("    // Blocked categories")
        for cat in blocked_cats:
            out.append(f"    // {cat.abbrev}  {cat.name} — {cat.description}")
            for pat in cat.patterns:
                out.append(f'    if (shExpMatch(host, "{pat}")) return "PROXY 127.0.0.1:1";')
        out.append("")

    if allow_rules:
        out.append("    // Allow rules — bypass proxy")
        for r in allow_rules:
            out.append(f'    if ({_pat(r)}) return "DIRECT";')
        out.append("")

    out.append("    // Default policy")
    if filter_engine.mode == FilterMode.DENYLIST:
        out.append(f'    return "SOCKS5 {proxy}";')
    else:
        out.append(f'    return "PROXY 127.0.0.1:1";  // ALLOWLIST — block by default')
    out.append("}")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(out) + "\n")


def generate_privoxy(
    filter_engine: FilterEngine,
    classifier,
    proxy_host: str,
    proxy_port: int,
    base: Path,
) -> tuple[Path, Path]:
    """Write a Privoxy user.action file and a config snippet.

    Returns (action_path, conf_path).

    Pattern translation:
      *.example.com  →  .example.com   (Privoxy dot-prefix = domain + all subdomains)
      sub.example.com → sub.example.com (exact host, unchanged)
      *.google.com.* and *.amazon.*    →  cannot translate (wildcard TLD); written as comments
    """
    def _to_privoxy(pat: str) -> str | None:
        p = pat.strip().lower()
        if p.count("*") >= 2:
            return None
        if p.startswith("*."):
            return "." + p[2:]
        return p

    deny_rules   = [r for r in filter_engine.rules if r.kind == RuleKind.DENY]
    allow_rules  = [r for r in filter_engine.rules if r.kind == RuleKind.ALLOW]
    blocked_cats = [
        c for c in classifier.categories
        if classifier.is_category_blocked(c.name)
    ]
    proxy = f"{proxy_host}:{proxy_port}"
    today = datetime.date.today()

    # ── user.action ────────────────────────────────────────────────────
    act: list[str] = [
        f"# Privoxy user.action — generated by sockLight — SOCKS5 Dev Proxy {today}",
        f"# SOCKS5 proxy: {proxy}  |  mode: {filter_engine.mode.value}",
        "#",
        "# Load this file in Privoxy config:",
        "#   actionsfile user.action",
        "#",
        "# To forward all traffic to the SOCKS5 proxy add to Privoxy config:",
        f"#   forward-socks5t   /   {proxy}   .",
        "",
    ]

    if filter_engine.mode == FilterMode.ALLOWLIST:
        act += [
            "# ALLOWLIST mode — block everything by default, then allow exceptions",
            "{ +block{default: allowlist mode} }",
            "/",
            "",
        ]

    if deny_rules:
        act.append("# ── Deny rules ──────────────────────────────────────────────────────")
        act.append("{ +block{deny rule} }")
        for r in deny_rules:
            pv = _to_privoxy(r.pattern)
            if pv:
                suffix = f":{r.port}" if r.port else ""
                act.append(f"{pv}{suffix}")
            else:
                act.append(f"# UNSUPPORTED (multi-wildcard TLD): {r.pattern}")
        act.append("")

    if blocked_cats:
        act.append("# ── Blocked categories ──────────────────────────────────────────────")
        for cat in blocked_cats:
            act.append(f"# {cat.abbrev}  {cat.name} — {cat.description}")
            act.append(f"{{ +block{{{cat.name}: {cat.abbrev}}} }}")
            for pat in cat.patterns:
                pv = _to_privoxy(pat)
                if pv:
                    act.append(pv)
                else:
                    act.append(f"# UNSUPPORTED (multi-wildcard TLD): {pat}")
            act.append("")

    if allow_rules:
        act.append("# ── Allow rules (override blocks) ───────────────────────────────────")
        act.append("{ -block }")
        for r in allow_rules:
            pv = _to_privoxy(r.pattern)
            if pv:
                suffix = f":{r.port}" if r.port else ""
                act.append(f"{pv}{suffix}")
            else:
                act.append(f"# UNSUPPORTED (multi-wildcard TLD): {r.pattern}")
        act.append("")

    # ── config snippet ─────────────────────────────────────────────────
    conf: list[str] = [
        f"# Privoxy config snippet — generated by sockLight — SOCKS5 Dev Proxy {today}",
        "#",
        "# Add these lines to your Privoxy config file (usually /etc/privoxy/config",
        "# or ~/.privoxy/config), then reload Privoxy.",
        "",
        "# Forward all traffic to SOCKS5 dev proxy",
        f"forward-socks5t   /   {proxy}   .",
        "",
        "# Load the exported action rules",
        f"actionsfile {base.stem}.action",
    ]

    action_path = base.with_suffix(".action")
    conf_path   = base.with_suffix(".conf.snippet")

    base.parent.mkdir(parents=True, exist_ok=True)
    action_path.write_text("\n".join(act) + "\n")
    conf_path.write_text("\n".join(conf) + "\n")
    return action_path, conf_path


def generate_adblock(
    filter_engine: FilterEngine,
    classifier,
    path: Path,
) -> int:
    """Write an Adblock Plus / uBlock Origin filter list.

    Returns number of filter rules written.

    Pattern translation:
      *.example.com   →  ||example.com^
      sub.example.com →  ||sub.example.com^
      multi-wildcard  →  written as comment (not supported)
    """
    def _to_adblock(pat: str, port: int | None = None) -> str | None:
        p = pat.strip().lower()
        if p.count("*") >= 2:
            return None
        if p.startswith("*."):
            host = p[2:]
        else:
            host = p
        return f"||{host}^"

    deny_rules = [r for r in filter_engine.rules if r.kind == RuleKind.DENY]
    blocked_cats = [
        c for c in classifier.categories
        if classifier.is_category_blocked(c.name)
    ]

    out: list[str] = [
        "[Adblock Plus 2.0]",
        f"! Title: sockLight export — {datetime.date.today()}",
        f"! Mode: {filter_engine.mode.value}",
        "! Generated by sockLight — SOCKS5 Dev Proxy",
        "!",
    ]
    n = 0

    if deny_rules:
        out.append("! ── Deny rules ──────────────────────────────────────────────────────")
        for r in deny_rules:
            ab = _to_adblock(r.pattern, r.port)
            if ab:
                out.append(ab)
                n += 1
            else:
                out.append(f"! UNSUPPORTED (multi-wildcard): {r.pattern}")
        out.append("!")

    if blocked_cats:
        out.append("! ── Blocked categories ──────────────────────────────────────────")
        for cat in blocked_cats:
            out.append(f"! {cat.abbrev}  {cat.name} — {cat.description}")
            for pat in cat.patterns:
                ab = _to_adblock(pat)
                if ab:
                    out.append(ab)
                    n += 1
                else:
                    out.append(f"! UNSUPPORTED (multi-wildcard): {pat}")
            out.append("!")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(out) + "\n")
    return n
